[package]
name = "multi-dimensional-plotter-rust"
version = "0.1.0"
authors = ["Charlotte Lily Fields <charlottelilyfields48@gmail.com>",
           "Andrea Pascal <andrea@anodium.net>"]

[dependencies]
